apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-04-23T11:05:42Z"
  generation: 1
  labels:
    app: nginx
  name: nginx
  namespace: nishant
  resourceVersion: "8239308"
  selfLink: /apis/apps/v1/namespaces/nishant/deployments/nginx
  uid: 51d7fb35-4108-4595-9cc8-79e694365d18
spec:
  imagePullSecrets:
- name: regcred
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
