apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-04-23T11:00:29Z"
  generation: 1
  labels:
    app: nginx
  name: nginx
  namespace: nishant
  resourceVersion: "8236937"
  selfLink: /apis/apps/v1/namespaces/nishant/deployments/nginx
  uid: 30045d76-54ca-42a4-aba4-ed1ddc869ffb
spec:
  imagePullSecrets:
  - name: regcred
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
